export default {
	growthRatio: 0.05,
	actions: {
		BUTTON_CLICK: 'BUTTON_CLICK',
		BUY_GENERATOR: 'BUY_GENERATOR',
		CHECK_STORY: 'CHECK_STORY',
		EXAMPLE: 'EXAMPLE_MUTATION',
		INCREMENT: 'INCREMENT'
	}
};
